google/libphonenumber

cpp/src/phonenumbers/utf/unilib.cc
fix from pagespeed change https://code.google.com/p/modpagespeed/source/detail?r=4389
=> fix handling broken unicode character hang

cpp/CMakeLists.txt
In #363 I said "If you were using a different version control system I'd send a pull request".  Well now you are, and here it is.
=> Add missing header files to install

README.md
We cannot host the compiled demo on github as github will not 'serve' html pages directly. This needs to be moved to somewhere like appspot and updated with the Java demo.
=> Updated README.md for latest version and removed broken line to googlecode for JS version.

javascript/i18n/phonenumbers/asyoutypeformatter_test.js
Workaround/fix for: https://github.com/googlei18n/libphonenumber/issues/658
=> Fixing tests

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
Merging in version update changes from maven release.
=> Staudacher update 7.0.6

java/carrier/src/com/google/i18n/phonenumbers/PhoneNumberToCarrierMapper.java, java/internal/prefixmapper/src/com/google/i18n/phonenumbers/prefixmapper/PrefixTimeZonesMap.java, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java
Fixed the JavaDoc that generated errors when compiling with Java 8.
=> Fix JavaDoc to comply with Java 8

resources/PhoneNumberMetadata.xml
=> Fix bad regex (trailing pipe) in Poland (PL) nationalNumberPattern.

java/libphonenumber/src/com/google/i18n/phonenumbers/AsYouTypeFormatter.java, java/libphonenumber/src/com/google/i18n/phonenumbers/NumberParseException.java, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberMatch.java, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, java/libphonenumber/src/com/google/i18n/phonenumbers/ShortNumberInfo.java, java/libphonenumber/src/com/google/i18n/phonenumbers/ShortNumberUtil.java, java/libphonenumber/src/com/google/i18n/phonenumbers/internal/MatcherApi.java
Reverts googlei18n/libphonenumber#764
=> Revert "removed some javadoc errors"

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
Update version numbers in Maven files.
=> Keghani update 7.0.9

java/libphonenumber/pom.xml, java/pom.xml, tools/java/common/pom.xml, tools/java/cpp-build/pom.xml, tools/java/java-build/pom.xml
The change breaks ant compilation in java/.
=> roll back https://github.com/googlei18n/libphonenumber/pull/868 (xml files only)

java/demo/src/com/google/phonenumbers/PhoneNumberParserServlet.java
~~Note that this is on top of PR #934.~~
Merged.
=> add permalink from result page to come back to that result

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
=> Penmetsaa update 7.2.3

java/build.xml
=> Delete obsolete resources

java/demo/src/com/google/phonenumbers/PhoneNumberParserServlet.java
The null phoneNumber already causes a NumberParseException anyway. Not changing release_notes.txt because this is in the same place as the other one I already fixed.
=> also catch phoneNumber null case in demo

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
Along with maven version updates, we have java/release_notes.txt(To remove pending changes line) update that is done manually.
=> Penmetsaa update 7.2.5

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
Maven: version updates in pom.xml for 7.2.7 release
=> Penmetsaa update 7.2.7

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
=> Penmetsaa update 7.2.8

FALSEHOODS.md
Made ITU question more concrete, changed wording in phone widget tip.
=> Falsehoods reordering and small fixes

resources/phonenumber.proto
PhoneNumber proto class documentation.
=> Update outdated comments about the national significant number in the

FAQ.md
FAQ. This will be referenced in release emails on the mailing list.
=> Adding a question about what we mean when we refer to metadata

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
=> Padmaksham update 7.3.0

FALSEHOODS.md
* #1009: Add point about each phone number having only one prefix.
* #1015: Add another example of `*` in phone numbers.
* #1027: Add point about relationship between number and owner's location.
* #1034: Add point about Italian leading zero.
=> merge some PRs into FALSEHOODS.md

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
=> Penmetsaa update 7.3.1

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
=> Padmaksham update 7.4.1

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
Libphonenumber version updates in pom.xml
=> Penmetsaa update 7.4.3

FALSEHOODS.md
* users only store phone numbers in phone number fields
* phone numbering plans published by governments represent reality
=> add two more falsehoods:

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml, pom.xml
This PR includes fixes for b/30130919 also.
=> Maven pom.xml updates for release 7.4.5

resources/carrier/ru/374.txt
=> Translate carrier for AM from en to ru

resources/carrier/en/382.txt
Hello,
I added the 382.txt for Montenegro carrier info.
Kind regards,
Milos
=> add montenegro (382) carrier info

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
Version number updates in pom.xml files.
=> Penmetsaa update 7.5.2

java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataManager.java, java/libphonenumber/src/com/google/i18n/phonenumbers/MultiFileMetadataSourceImpl.java, java/libphonenumber/src/com/google/i18n/phonenumbers/SingleFileMetadataSourceImpl.java, java/pending_code_changes.txt
b/30669304
b/30726034
b/30807096
=> Refactor metadata loading and close all streams after loading metadata

resources/carrier/en/86.txt
Pull request for issue #1259 . Updated the carrier mappings for China provided by ChinaMobile
=> Updated China carrier data mappings

.travis.yml, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java
Not doing demo: needs appengine sdk to work.
Fixed smart-quotes that stopped it building on my machine.
=> Continuous build for Ant.

cpp/CMakeLists.txt
=> Update CMakeLists.txt minor version to 5

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
=> 7 6 1 maven

tools/java/common/src/com/google/i18n/phonenumbers/BuildMetadataFromXml.java
=> Fix C++ serialization bug with builder

cpp/test/phonenumbers/phonenumberutil_test.cc
-- changing to use ULL in test numbers so this compiles on all platforms
-- updating a couple of test-cases/comments to bring inline with Java
=> Small test fixes (C++)

java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataLoader.java
=> Clarify the need and responsibilites of MetadataLoader interface

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
Version number updates in Maven pom.xml files.
=> Penmetsaa update 7.7.1

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
Version number updates in Maven pom.xml files during release 7.7.2
=> Maven update 7.7.2

README.md
Version number update in README.md
=> Update README.md for release 7.7.2

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
pom.xml updates for release 7.7.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1404)
=> Maven update

cpp/test/phonenumbers/phonenumberutil_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1410)
=> Correct comment in phonenumberutil_test.cc

FALSEHOODS.md
Attempted to clarify the wording around the 800 country code, which is distinct from the 800 area code, and was initially confusing (to me).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1413)
=> Minor rewording for clarification

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1441)
=> Add versioning documentation

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
Maven pom.xml updates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1445)
=> Maven update for release 7.7.5

cpp/src/phonenumbers/shortnumberinfo.cc, cpp/src/phonenumbers/shortnumberinfo.h, java/libphonenumber/src/com/google/i18n/phonenumbers/ShortNumberInfo.java, java/pending_code_changes.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1457)
=> Method deletion for ShortNumberInfo deprecated methods.

cpp/src/phonenumbers/shortnumberinfo.cc
** do not copy these notes into final commit **
b/29962370
Tested:
```
export PATH=/usr/local/buildtools/java/jdk7/bin:$PATH &&\
mvn clean &&\
( cd tools/java/ && mvn package) &&\
mkdir -p cpp/build/ &&\
( cd cpp/build/ && cmake -DUSE_LITE_METADATA=OFF .. && make ) &&\
( cd cpp/build/ && cmake -DUSE_LITE_METADATA=ON .. && make ) &&\
( cd cpp/build/ && cmake .. && make && ./libphonenumber_test ) &&\
ant -f java/build.xml build-phone-metadata build-test-metadata build-short-metadata build-alternate-metadata build-timezones-data build-timezones-test-data junit &&\
ln -s ~/.libphonenumber/closure-library/ ../closure-library &&\
ln -s ~/.libphonenumber/closure-compiler/ ../closure-compiler &&\
ant -f java/build.xml build-js-metadata &&\
ant -f javascript/build.xml compile-demo compile-tests …
```
=> Remove unused scope_ptr include

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1499)
=> Update 'Known Ports' section in README to emphasize quality disclaimer

README.md
Resolves https://github.com/googlei18n/libphonenumber/issues/1332
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1500)
=> Add C# port to README

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1506)
=> maven pom.xml updates for release 8.0.1

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
Maven pom.xml updates for release 8.1.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1523)
=> Penmetsaa maven update

cpp/test/phonenumbers/phonenumberutil_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1525)
=> Removing unneeded helper functions in tests, fixing typo.

java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, java/pending_code_changes.txt, javascript/i18n/phonenumbers/phonenumberutil.js, javascript/i18n/phonenumbers/phonenumberutil_test.js
making use of it in the code in parallel places to the Java
implementation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1526)
=> Make normalizeDiallableCharsOnly public and port it to javascript,

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1550)
=> Sumathisundara maven update

resources/geocoding/en/972.txt, resources/geocoding/he/972.txt, resources/geocoding/iw/972.txt
For https://github.com/googlei18n/libphonenumber/issues/1557
Since this is the first entry for language HE, does it need to be added to a list somewhere?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1563)
=> Add HE localization for 972

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1572)
=> maven pom.xml updates for release 8.3.0

CONTRIBUTING.md, FAQ.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1577)
=> Document Windows caveats

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1586)
=> maven pom.xml updates for release 8.3.1

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1587)
=> Update demo version in README.md

FAQ.md
b/29382143
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1598)
=> Add FAQ for Android resource loading

FAQ.md
Antarctica etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1620)
=> Adding FAQ about why we don't support countries like Bouvet Island,

CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1624)
=> Update contribution guidelines for libphonenumber-supporting-docs

FAQ.md, cpp/README
Addresses #1010 
b/27688547
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1597)
=> Update Visual Studio documentation

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1632)
=> maven pom.xml updates for release 8.3.3

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1639)
=> Adding a link to the latest javadoc

java/demo/pom.xml, java/demo/src/com/google/phonenumbers/PhoneNumberParserServlet.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1646)
=> Make demo show UTF-8 chars for a single result & fixing to work with mvn

FAQ.md, README.md
Fixing a lot of broken links too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1655)
=> Adding a FAQ about the metadata-lite files

FAQ.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1656)
=> Fix bullets in FAQ

CONTRIBUTING.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1653)
=> Update instructions to clarify steps for Individual and Corporate CLA signatures

cpp/src/phonenumbers/phonenumberutil.cc, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, tools/java/common/src/com/google/i18n/phonenumbers/MetadataFilter.java
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1661)
=> Update comments re. metadata filter

FAQ.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1667)
=> Update Windows known issues

FAQ.md
Inspired by #1645
b/36428464
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1669)
=> Document how to find the jar library versions for carrier/geocoding/prefixmapper

cpp/src/phonenumbers/phonenumberutil.h, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, javascript/i18n/phonenumbers/phonenumberutil.js, pending_code_changes.txt
getRegionCodeForNumber clarification about it not working for short codes or non-valid numbers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1673)
=> Docs change

javascript/build.xml
Tested and it detected goog.object was missing!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1674)
=> Adding secret option which *really* catches all missing requires. 

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1698)
=> Update known ports, includes #1590

javascript/i18n/phonenumbers/phonenumberutil_test.js
b/37535740
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1702)
=> Fix duplicate variable initialization

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1705)
=> maven pom.xml updates for release 8.4.2

README.md
Replacement for PR #1564
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1714)
=> Explaining more about the JS ports and adding seegno's port.

README.md, resources/timezones/README.md
cl/154937783
b/29383121
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1721)
=> Add timezone mapper readme

FAQ.md
cl/154932097
b/28334035
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1723)
=> Add FAQ about 803 usage in Indonesia.

FAQ.md
Add more context how it's not just more metadata sources/countries we need, but also how to technically support M2M.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1718)
=> Update M2M FAQ with more specific requests

resources/timezones/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1728)
=> Update timezone mapper README with CLDR translated name pointers

cpp/README
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1735)
=> Fix a typo in cpp/README

cpp/src/phonenumbers/matcher_api.h, cpp/src/phonenumbers/phonenumberutil.cc, cpp/src/phonenumbers/phonenumberutil.h, cpp/src/phonenumbers/regex_based_matcher.cc, cpp/src/phonenumbers/regex_based_matcher.h, cpp/src/phonenumbers/shortnumberinfo.cc, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, java/libphonenumber/src/com/google/i18n/phonenumbers/ShortNumberInfo.java, java/libphonenumber/src/com/google/i18n/phonenumbers/internal/MatcherApi.java, java/libphonenumber/src/com/google/i18n/phonenumbers/internal/RegexBasedMatcher.java
cl/154533233
b/37494614
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1749)
=> Update call sites using the national number pattern to do so through MatcherApi

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1755)
=> Maven pom.xml updates for release 8.5.0

java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, javascript/i18n/phonenumbers/phonenumberutil.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1770)
=> Fixing typos in a couple of method descriptions.

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1774)
=> maven pom.xml updates for release 8.5.1

cpp/src/phonenumbers/geocoding/mapping_file_provider.h, cpp/src/phonenumbers/geocoding/phonenumber_offline_geocoder.h, java/geocoder/src/com/google/i18n/phonenumbers/geocoding/PhoneNumberOfflineGeocoder.java, java/internal/prefixmapper/src/com/google/i18n/phonenumbers/prefixmapper/MappingFileProvider.java, java/internal/prefixmapper/src/com/google/i18n/phonenumbers/prefixmapper/PrefixFileReader.java
E.g. where there are iw and he, which one we should use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1776)
=> Comment changes to clarify which language code to use

tools/java/common/test/com/google/i18n/phonenumbers/BuildMetadataFromXmlTest.java
cl/158701188
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1788)
=> Add tests for [-1] possible lengths

tools/java/common/test/com/google/i18n/phonenumbers/MetadataFilterCoverageTest.java, tools/java/common/test/com/google/i18n/phonenumbers/MetadataFilterTest.java
cl/159424541
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1795)
=> Update MetadataFilter tests

FAQ.md
cl/159208179
b/62609422
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1806)
=> Update AR and MX FAQ

cpp/src/phonenumbers/regex_based_matcher.cc, cpp/src/phonenumbers/regex_based_matcher.h, cpp/test/phonenumbers/geocoding/area_code_map_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1820)
=> Remove unused includes

cpp/src/phonenumbers/phonenumberutil.h, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, javascript/i18n/phonenumbers/phonenumberutil.js, pending_code_changes.txt
to compare and contrast with parseAndKeepRawInput
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1825)
=> Comment improvements for parse

CONTRIBUTORS, cpp/src/phonenumbers/phonenumberutil.cc, cpp/src/phonenumbers/phonenumberutil.h, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, javascript/i18n/phonenumbers/phonenumberutil.js, pending_code_changes.txt
cl/160939124
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1838)
=> Minor update to documentation in PhoneNumberUtil

FAQ.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1844)
=> Adding FAQ about parsing and national prefixes.

java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberMatcher.java, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, java/libphonenumber/src/com/google/i18n/phonenumbers/ShortNumberInfo.java, java/libphonenumber/test/com/google/i18n/phonenumbers/PhoneNumberUtilTest.java, pending_code_changes.txt
Also removed two private methods that were unused (leftover from a previous commit).
Addresses github issue #84
=> Replacing some public APIs that take phone numbers as strings with CharSequence.

cpp/src/phonenumbers/phonenumbermatcher.cc, cpp/test/phonenumbers/regexp_adapter_test.cc
Fixes #724
Not to be submitted now, due to release.
=> Fix USE_RE2 ifdef

FAQ.md
=> FAQ for #1870

cpp/src/phonenumbers/phonenumberutil.cc, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, pending_code_changes.txt
Don't log client-provided phone numbers.
=> Staudacher pii logging

cpp/src/phonenumbers/phonenumberutil.cc, cpp/src/phonenumbers/phonenumberutil.h, pending_code_changes.txt
=> Add constants for C++ util's enum's max values

FALSEHOODS.md
Addresses https://github.com/googlei18n/libphonenumber/issues/1921
=> Add vanity numbers in falsehoods

javascript/i18n/phonenumbers/phonenumberutil.js
=> Fix JS issue

javascript/i18n/phonenumbers/phonenumberutil.js
=> Fix for typing issue

FAQ.md, pending_code_changes.txt, tools/cpp/src/cpp-build/generate_geocoding_data.cc
b/31256592
Fixes #1307
Relevant man pages:
https://linux.die.net/man/3/readdir
https://linux.die.net/man/3/errno
=> Move from readdir_r to readdir

pending_code_changes.txt, tools/java/cpp-build/pom.xml
See b/67581460 for background and testing.
This has also 0 impact on the release (test: https://github.com/keghani/libphonenumber/pull/5)
=> Update protoc dep to 3.0.0

FAQ.md
=> Update valid number FAQ

release_notes.txt
See https://github.com/googlei18n/libphonenumber/releases/tag/v8.0.0
=> Update v8.0.0 release notes

FAQ.md
To reformat or not to reformat?
=> New formatting FAQ

pending_code_changes.txt
@dimbleby FYI
I had forgotten about this earlier... We're probably cutting the release tomorrow, until then if you have a better wording suggestion please chime in. We can also change this later.
=> Add pending code change snippet for RPM build fix

CONTRIBUTING.md
Reordering of sections since many folks seem to skip the metadata / issue filing guidelines
=> CONTRIBUTING.md reorg

README.md
=> Listing the Rust port of libphonenumber

CONTRIBUTING.md
Make the demo link more obvious by putting it first, add note about the temporary transition to Issue Tracker, and mention Google Product Forums
=> Reorg + Issue Tracker transition

java/demo/war/WEB-INF/appengine-web.xml
See https://cloud.google.com/appengine/docs/standard/java/migrating-to-java8
=> Update App Engine to runtime=java8

java/demo/src/com/google/phonenumbers/PhoneNumberParserServlet.java
As part of transition to Google Issue Tracker from GitHub Issues making this update.
Announcement done at: https://groups.google.com/forum/#!topic/libphonenumber-discuss/-M3YjdkkOiA
=> Update new issue creation link in demo portal to direct to Issue Tracker instead of GitHub

FAQ.md
Due to migration from Github issues to Issue Tracker.
=> Update link to main M2M issue

pending_code_changes.txt
This is followup of PR: https://github.com/googlei18n/libphonenumber/pull/2184
=> Update pending_code_changes.txt w.r.t PR: #2184

javascript/i18n/phonenumbers/phonenumberutil.js
Removing special/garbage character (not seeable with human eye in file). This is introduced in PR #2184 as this is not visible. Removed characters and added spaces again.
=> Remove unknown character from phonenumberutil.js

CONTRIBUTING.md
Policy update to prefer creating bug / email public discussion group than PR for issues that are specific to particular build / setup. eg: #2222
=> Update CONTRIBUTING.md for

cpp/src/phonenumbers/geocoding/phonenumber_offline_geocoder.cc, cpp/src/phonenumbers/phonenumberutil.cc, cpp/src/phonenumbers/stl_util.h, cpp/test/phonenumbers/regexp_adapter_test.cc
Updating references in code. Removing an unused using declaration.
=> Moving stl helper functions into inner namespace (gtl::).

cpp/src/phonenumbers/phonenumberutil.cc, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, java/libphonenumber/test/com/google/i18n/phonenumbers/PhoneNumberUtilTest.java, javascript/i18n/phonenumbers/phonenumberutil.js
- Making source code ASCII safe.
- And few other corrections in order to be consistent.
=> Cleanup in continuation to support of Russian extension characters

javascript/i18n/phonenumbers/phonenumberutil_test.js
This variable was instantiated twice so I removed one.
=> Remove redundant assignment

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
=> Rnidhi maven update

javascript/i18n/phonenumbers/phonenumberutil.js, javascript/i18n/phonenumbers/phonenumberutil_test.js, javascript/i18n/phonenumbers/shortnumberinfo.js
Like not null parameters. This is followup to recent cl/300367316. (#2443)
More details in cl/301500293
=> Make JS util test changes to reflect the annotation updates.

README.md
And also that we will fix it soon.
=> Update README to mention that JS demo is not working.

cpp/CMakeLists.txt, cpp/README
This pull request is a copy of the REGENERATE_METADATA modification on 
https://github.com/google/libphonenumber/pull/2363
The modification was made by @Venemo , but #2363 included several options
@penmetsaa asked split the PR
@battre I suggest you look also
=> Add new build options REGENERATE_METADATA (Original commit from  Timur Kristóf)

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
=> Mavem pom.xml updates for release 8_12_5

metadata/README.md
This is just a placeholder to create the directory, the source files will be pushed once this is in.
=> Add README for new metadata directory

metadata/src/main/java/com/google/i18n/phonenumbers/metadata/table/CsvParser.java
PiperOrigin-RevId: 319993252
Changes only made by Googlers, so CLA is implicit.
=> Avoid using internal only Guava method.

metadata/.gitignore, metadata/pom.xml
PiperOrigin-RevId: 320027220
Googler only contributions, so CLA is fine.
=> Adding Maven POM file and .gitignore for Maven & IntelliJ

metadata/pom.xml
PiperOrigin-RevId: 322109913
Internal changes, no CLA issues.
=> A few tweaks to make the metadata pom file more suitable in IntelliJ.

README.md
Update JavaScript demo URL to use htmlpreview
=> Update JavaScript demo URL to use htmlpreview

cpp/src/phonenumbers/phonenumberutil.cc
Removing unused var, indent fix.
=> Small fixes to phonenumberutil.cc

FAQ.md
This is with regards to setting up the expectations like "We cannot commit on any deadlines" though we are sure of the approach after weighing the ramifications. Make it clear that M2M use case are diverse and its demand for new Util API.
=> Update M2M FAQ

.github/workflows/unit-test.yml
- When configured "pull_request[type: opened] + push", workflow not getting triggered when there is a change in PR code/commits when the branch is from the parent's forked repo.
- Configured only pull_request event as any change can only go through PR. 
- pull_request event by default happens when opened, synchronize (means whenever there is change/commit, sync happens), and reopened. So this should be good enough for our use cases.
More details in [approach doc](https://docs.google.com/document/d/1YNYUAlEUXTi4UZG5gEFZGQ7oe7LxNKh7FYSg2qtIUvI/edit#heading=h.1c7qt5y1jb9)
=> Update event list for workflow triggering.

FAQ.md
Inspired from https://issuetracker.google.com/issues/198423548
More details mentioned there.
=> Update FAQ about "why parsed national number is different in JS".

metadata/pom.xml, metadata/src/main/java/com/google/i18n/phonenumbers/metadata/model/FormatSpec.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/RangeTreeTest.java
- This change is only for some metadata/ apis only.
- Bumped up java version for this.
More details in cl/396604897
=> Use new String APIs in place of util apis of Strings.

cpp/src/phonenumbers/regexp_adapter_icu.cc, cpp/src/phonenumbers/stringutil.cc
After reading comment from @katbohm and @penmetsaa on #2703 and #2711, I created this PR for faster itoa.
Using abseil function, SimpleItoa create less several temporary object than previous version and give speed improvement
=> Accelerate SimpleItoa conversion using abseil function

cpp/src/phonenumbers/shortnumberinfo.cc, cpp/src/phonenumbers/shortnumberinfo.h
=> shortnumberinfo.cc updates: Using absl collections; using nullptr instead of NULL where needed.

java/libphonenumber/src/com/google/i18n/phonenumbers/metadata/source/BlockingMetadataBootstrappingGuard.java
Replacing usage of `HashSet` with `ConcurrentHashMap`. 
While it is unlikely that the concurrency causes `HashSet#contains` to return `true` when the set does not contain the element, the Java memory model allows other weird behaviors. For example, it is an acceptable behaviour to throw a `NullPointerException` when the backing array is being resized and another thread tries to access it.
=> Fixing data race in BlockingMetadataBootstrappingGuard

release_notes.txt
- This data will be part of next release. More details in b/234419524
=> Update release_notes.txt, reverting notes about inclusion of CSV metadata

release_notes.txt
More context in b/234419524 and b/143267727
=> Update release notes based on new CSV metadata files.

cpp/src/phonenumbers/phonenumberutil.h, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java
Updated docs of formatInOriginalFormat to indicate it should be used after parseAndKeepRawInput
=> Updated docs of formatInOriginalFormat

javascript/i18n/phonenumbers/demo.js
=> Updating the upstream to use JS's JSON api 'Stringify' rather than Google closure apis

java/demo/README, java/demo/README.md
Added mac setup instructions in addition to the linux setup instructions for the demo
=> added Mac setup instructions

cpp/README
Fixes:
https://issuetracker.google.com/issues/251742470
=> Updated the C++ installation instructions

README.md
I am mentioning note about present deplyment issue of demo portal and which version it is in.
=> Update Readme for release 8.12.57

java/demo/pom.xml, java/demo/src/main/java/com/google/phonenumbers/demo/render/ErrorRenderer.java, java/demo/src/main/java/com/google/phonenumbers/demo/render/InputFormRenderer.java, java/demo/src/main/java/com/google/phonenumbers/demo/render/LibPhoneNumberRenderer.java, java/demo/src/main/java/com/google/phonenumbers/demo/render/ResultFileRenderer.java, java/demo/src/main/java/com/google/phonenumbers/demo/render/ResultRenderer.java
Using precompiled templates with SoySauce instead of Tofu runtime interpreter
=> Using precompiled templates with SoySauce

java/demo/src/main/webapp/WEB-INF/web.xml
This is followup after https://github.com/google/libphonenumber/pull/2839
=> Adding servlet mapping for java demo's landing page

cpp/src/phonenumbers/test_metadata.cc
This is a continuation of #2762
=> Make tests use test metadata

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
This reverts commit 400bc9cf1d5664a08b5baf8127dc694fa5f92335.
=> Revert "Kkeshava maven update (#2844)"

.github/workflows/scorecards.yml
Reverts google/libphonenumber#3130
=> Revert "Bump ossf/scorecard-action from 2.0.6 to 2.2.0"

java/pom.xml
maven-source-plugin:goal has changed jar to jar-no-fork
=> Update pom.xml 

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
Reverts google/libphonenumber#3403
Java8 is changed to java11
=> Revert "Kkeshava maven update"

FALSEHOODS.md
I really enjoyed using this project, nice work! Caught a couple of typos in the FALSEHOODS.md though 😛
=> Update FALSEHOODS.md, fix typo(s)

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
Reverts google/libphonenumber#3858
Demo is failing due to app-engine-java missing package
=> Revert "Rnidhi maven update"
