google/libphonenumber

cpp/src/phonenumbers/asyoutypeformatter.cc, java/libphonenumber/src/com/google/i18n/phonenumbers/AsYouTypeFormatter.java, javascript/i18n/phonenumbers/asyoutypeformatter.js
in its Java implementation when extracting the Chinese national prefix 17951 and didn't reset the format template / lastMatchPosition.
Includes corresponding changes for C++ and JavaScript as well to keep the implementations in sync. (C++ and JS didn't exhibit buggy behavior because the corresponding substring methods don't throw errors for invalid start positions.)
Bugfix for https://github.com/googlei18n/libphonenumber/issues/592
=> Fix bug in AsYouTypeFormatter where we hit a IndexOutOfBoundsException

cpp/src/phonenumbers/asyoutypeformatter.cc, javascript/i18n/phonenumbers/asyoutypeformatter.js
Follow up from change 49c2427, copying the comment from the Java implementation to the C++ impl.
(In response to the code review from https://github.com/googlei18n/libphonenumber/pull/614)
=> Add comment

cpp/src/phonenumbers/asyoutypeformatter.cc, cpp/src/phonenumbers/base/logging.h, cpp/test/phonenumbers/geocoding/geocoding_test_program.cc
Fix unused-variable warnings when building with CMAKE_BUILD_TYPE=RELEASE
=> Clean compile with CMAKE_BUILD_TYPE=RELEASE

debian/watch
The old libphonenumber/libphonenumber has been abandoned in favour of
the new googlei18n/libphonenumber project.
=> Update debian/watch URL to point to new GitHub project.

resources/geocoding/en/1.txt
The geocoding file for English had both *Quebec* and *Québec* for the canadian
state and city. *Québec* is the French spelling, while *Quebec* is the correct
English spelling.
=> Minor: Replace Québec => Quebec in geocoding files

resources/PhoneNumberMetadata.xml
=> In Belarus, add Beltelcom's Maxiphone range (+375 24 9xxxxxx) as VOIP.

resources/timezones/map_data.txt
This was accidentally updated by script, and should have been left as the original year.
=> revert timezones map_data copyright year

cpp/CMakeLists.txt
This reverts commit df876cedb52454f6212f39513c4d5fe7eacdf71e.
This commit broke internal builds with the error message:
----
CMake Error at CMakeLists.txt:422 (target_link_libraries):
Cannot specify link libraries for target "phonenumber" which is not built
by this project.
----
=> Revert "RPM packaging"

cpp/test/phonenumbers/shortnumberinfo_test.cc
Test scripts were failing if compiled as release builds, that is via `cmake -DCMAKE_BUILD_TYPE=RELEASE`.
That's because necessary parsing was happening inside an assertion that gets compiled out.  This fixes that.
=> Test scripts pass in release builds too

README.md
To be consistent with [Google JavaScript Style Guide](http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml), the word _JavaScript_ should be in upper camel case.
=> :s/Javascript/JavaScript/

CONTRIBUTORS, resources/geocoding/en/358.txt, resources/geocoding/fi/358.txt, resources/geocoding/se/358.txt
This is a copy of https://codereview.appspot.com/174570043/ . Since there was no activity there and libphonenumber has now moved to github, here is a PR instead.
Per http://www.viestintavirasto.fi/attachments/maaraykset/Maarays_32.pdf
(official numbering plan), in Finland (+358):
- 020*: National service and subscriber numbers
- 029*: National subscriber numbers
- 030*: National service and subscriber numbers
- 039*: National subscriber numbers
- 060*: National service numbers
- 0800*: National toll-free service numbers
The local subscriber numbers starting with 02,03,06,08 have 1..8 as
their third number.
However, libphonenumber assigns 02*, 03*, 06* and 08* to specific
locations in their entirety, causing e.g. some national service numbers
to be incorrectly geocoded.
Instead of using …
=> Exclude non-local service and national numbers from geocoding in Finland

java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java
Returning in finally blocks can be dangerous: 
https://weblogs.java.net/blog/2007/06/27/dont-return-finally-clause
=> Remove return from finally block.

cpp/src/phonenumbers/base/basictypes.h, tools/cpp/src/base/basictypes.h
This is a cherry-pick from the Chromium project, from where this
implementation of basictypes.h once originated:
https://chromium.googlesource.com/chromium/src/+/539fc83
=> When using C++11, use static_assert to implement COMPILE_ASSERT.

cpp/src/phonenumbers/base/basictypes.h, tools/cpp/src/base/basictypes.h
I missed this when copying Chromium code in pull request #742 to fix #725.
=> Replace defined(COMPILER_GCC) with defined(__GNUC__).

java/libphonenumber/pom.xml
Before this change, running ```mvn package``` form java/libphonenumber adds the following JARs in java/libphonenumber/target
```
libphonenumber-7.2.1-SNAPSHOT.jar
libphonenumber-7.2.1-SNAPSHOT-javadoc.jar
libphonenumber-7.2.1-SNAPSHOT-sources.jar
```
After this change it adds
```
libphonenumber-7.2.1-SNAPSHOT.jar
libphonenumber-7.2.1-SNAPSHOT-javadoc.jar
libphonenumber-7.2.1-SNAPSHOT-sources.jar
original-libphonenumber-7.2.1-SNAPSHOT.jar
``` 
where libphonenumber-7.2.1-SNAPSHOT.jar contains protobuf dependencies.
Diffs: ~keghani/GitHub_diffs/bbba20d
* libphonenumber-7.2.1-SNAPSHOT.jar CHANGED (78.6%):
+ Added 298 com/google/protobuf/ Java classes
+ Added META-INF/maven/com.google.protobuf/protobuf-java/pom.xml
+ Added META-INF/maven/com.google.protobuf/protobuf-java/pom.properties
+ Added …
=> Include protobuf dependencies in libphonenumber.jar

java/release_notes.txt
Nov 11, 2015: libphonenumber-7.2.1
Metadata changes: None
Fix to 7.2.0
=> Metadata updates for release 7.2.1

resources/PhoneNumberMetadata.xml
This change removes Austrian +43 numbering resources 802, 644, 711:
- The 802 and 644 date of deletion can be found at the end of https://www.rtr.at/de/tk/E129/2312_Austrian_Numbering_Plan_2011-03-30.pdf
- The 711 date of deletion at https://www.rtr.at/en/tk/Abschaltungen
=> Remove deprecated Austrian numbering resources; resolves #857

java/demo/pom.xml, java/demo/src/com/google/phonenumbers/PhoneNumberParserServlet.java
1. Use the standard UTF_8 String constant (available since Java 1.7).
2. Set the character encoding for when the input was a file (previously only set when the input was a single input but not a file).
3. Refactor getOutputForSingleNumber so that the HTML generated is self-contained. (Previously, the BODY and HTML closing tags were written outside of the if block for whether it's a single input or a file, leading to the tags being erroneously written twice when it's a file.)
4. Fix a minor bug where whether a newline is printed after the language code was dependent on whether a region code is present.
Edit: 5. Fix an existing bug which allows XSS attack through the inputs.
=> refactoring of demo with bug fixes including XSS fix

java/libphonenumber/src/com/google/i18n/phonenumbers/MultiFileMetadataSourceImpl.java, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, java/release_notes.txt
The exception occurs when getMetadataForNonGeographicalRegion is called with a country calling code which doesn't correspond to a non-geographic entity.
Also fix a typo in PhoneNumberUtil.
=> Fix IllegalStateException in MultiFileMetadataSourceImpl

cpp/CMakeLists.txt
Two issues:
a) add_custom_target test is a reserved keyword - changed to tests
b) there has been a policy change regarding RPATH. I could explicitly set the policy, but I think it's reasonable to just bump the version of cmake used. Chose 3.1 since it's sufficient but older.
=> Fixing cmake issues on mac

debian/control
This has become necessary after commit 15084a9.
=> Require CMake packages to be version 3.1 or higher.

cpp/CMakeLists.txt
This is necessary to guarantee that parallel builds will succeed, all
top-level targets that include geocoding_data.cc in their builds need
explicitly listed dependencies on generate_geocoding_data to ensure that
generation of the file has finished before it is being used.
=> Explicitly add dependencies on generate_geocoding_data.

cpp/src/phonenumbers/phonenumbermatcher.cc
The "-" range operator was duplicated as the end of the range as well, causing re2 to fail (and some test failures with newer versions of ICU apparently in some configurations)
=> Fixing issue with reg-exp when finding phone numbers in text

cpp/test/phonenumbers/phonenumbermatcher_test.cc
Fixed issue with failing tests for users who choose not to use alternate formats.
Added "ifdef" around the entries in phonenumbermatcher_test that require alternate formats to be included to be found. This means that if the user doesn't have this option set to true, the tests won't be run (they would otherwise fail).
=> Adding ifdef I18N_PHONENUMBERS_USE_ALTERNATE_FORMATS in phonenumbermatcher_test

cpp/src/phonenumbers/phonenumberutil.cc, cpp/src/phonenumbers/phonenumberutil.h, cpp/test/phonenumbers/phonenumberutil_test.cc, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, java/libphonenumber/test/com/google/i18n/phonenumbers/ExampleNumbersTest.java, java/libphonenumber/test/com/google/i18n/phonenumbers/PhoneNumberUtilTest.java, java/pending_code_changes.txt, javascript/i18n/phonenumbers/phonenumberutil.js
* New useful getExampleNumber methods (for testing) - one for invalid
numbers and one for getting a number of a particular type without
specifying a country.
=> Parse documentation and exampleNumber updates

cpp/CMakeLists.txt, cpp/README, debian/control, java/pending_code_changes.txt
This is similar to the fix of #822.
Also update README to cover Mac installation.
This rolls back the cmake minimum version bump in #975 since it was
backwards-incompatible, and the following #984. Not expected to cause
any new user-facing regressions, but expected to solve any that were
introduced with #975.
=> Add cmake Mac flag to enable Linux builds at lower cmake versions.

tools/cpp/src/cpp-build/generate_geocoding_data.cc
Implicit cast to bool does not work with C++11 and later. See http://en.cppreference.com/w/cpp/io/basic_ios/operator_bool
=> Explicitly call std::stringstream::fail()

java/libphonenumber/pom.xml
Repackage the Java `protobuf` library that is included in the libphonenumber source with a different package name to avoid conflicts with other projects.
A temporary workaround for #913, until [protobuf-javanano](http://mvnrepository.com/artifact/com.google.protobuf.nano/protobuf-javanano) is stable.
Contributed on behalf of @mingtaozhangsc.
=> Repackage java protobuf library

cpp/src/phonenumbers/regexp_adapter_re2.cc
A future change to RE2 will replace the VariadicFunction2 objects with variadic
templates, which would break the code in libphonenumber as it currently stands.
=> Make DispatchRE2Call() and its callers use the array-oriented functions in RE2.

resources/geocoding/fa/93.txt
I translated English Version of Afghanistan geocoding to Persian.
Note: One of two official languages in Afghanistan is Persian Dari Persian/ Dari Farsi.
=> Persian localized version of Afghanistan geocoding

java/demo/pom.xml, java/libphonenumber/pom.xml, java/pom.xml, tools/java/common/pom.xml, tools/java/cpp-build/pom.xml, tools/java/data/pom.xml, tools/java/java-build/pom.xml
Fixes b/22840154 and b/29343414.
Tested by running `mvn package` from root.
Still have javadoc warnings and errors (b/29977680, b/27241869, b/27241398), but everything else is cleaned up with this change.
Does not check in changed generated jars because their generation is currently not hermetic and outdated anyway (b/29546716); the output would not change either as a result of the changes in this PR in `tools/java/cpp-build/pom.xml` and `tools/java/java-build/pom.xml`, these changes actually bring us closer to being hermetic (b/24799921).
=> Fix Maven project hierarchy and plugin versions

java/libphonenumber/src/com/google/i18n/phonenumbers/MetadataLoader.java, java/libphonenumber/src/com/google/i18n/phonenumbers/MultiFileMetadataSourceImpl.java, java/libphonenumber/test/com/google/i18n/phonenumbers/MultiFileMetadataSourceImplTest.java, java/pending_code_changes.txt
Also removes point of contention for getting metadata when it's already been loaded.
b/30156489, b/24455712, b/30158468
=> Simplify concurrent metadata loading in MultiFileMetadataSourceImpl

java/lib/protobuf-javanano-readme.md
Tested: output is the same.
This was enabled by the change at https://github.com/google/protobuf/commit/801e92007fd6eac3fa5b4c386ba54089393680c7
b/24799921
=> Simplify javanano command-line

resources/carrier/en/27.txt
Updated +27 carrier data mappings with the information provided by the South African Mobile portability company issue : https://github.com/googlei18n/libphonenumber/issues/1242
=> Updated ZA carrier codes for numbers in the 27625-27647 range.

java/lib/protobuf-javanano-readme.md
To help with #1308 :)
We need to automate this generation at some point. b/31288274
Tested: Deleted `Phonemetadata.java` in a local git repository synced to master head, ran the 2 commands, and got back to exactly the original state.
=> Add convenience instructions to quickly update Phonemetadata.java

tools/java/java-build/src/com/google/i18n/phonenumbers/BuildMetadataJsonFromXml.java
Long-term we should fix the code that's setting these fields and remove
this workaround.
b/31541333
=> Stop JSON serialization from setting what should be empty fields

java/geocoder/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
This takes the patch submitted for #205 and modifies it to be a bit less intrusive with how it adds the OSGi meta-data.
This patch follows the mechanism described here: http://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html#adding-osgi-metadata-to-existing-projects-without-changing-the-packaging-type
How this works is that the `maven-bundle-plugin` is used to generate a `MANIFEST.MF` containing the necessary OSGi meta-data at build time, then the `maven-jar-plugin` is configured to utilize this built `MANIFEST.MF` file instead of generating it's own, everything else about the build process is left untouched.
=> add OSGi meta-data to libphonenumber and geocoder

FAQ.md
on why country-calling-code is not always parsed from the start of a phone number.
See e.g. issue #1374
=> Added parsing FAQ

java/pending_code_changes.txt, java/pom.xml
Change tag format as requested in https://github.com/googlei18n/libphonenumber/issues/1362
Tested:
Running mvn locally gives the existing jar naming format, so the Maven Central jars are not expected to change:
```
carrier-1.47-SNAPSHOT.jar
carrier-1.47-SNAPSHOT-javadoc.jar
carrier-1.47-SNAPSHOT-sources.jar
demo-7.7.4-SNAPSHOT.jar
demo-7.7.4-SNAPSHOT-javadoc.jar
demo-7.7.4-SNAPSHOT-sources.jar
geocoder-2.57-SNAPSHOT.jar
geocoder-2.57-SNAPSHOT-javadoc.jar
geocoder-2.57-SNAPSHOT-sources.jar
prefixmapper-2.57-SNAPSHOT.jar
prefixmapper-2.57-SNAPSHOT-javadoc.jar
prefixmapper-2.57-SNAPSHOT-sources.jar
libphonenumber-7.7.4-SNAPSHOT.jar
libphonenumber-7.7.4-SNAPSHOT-javadoc.jar
libphonenumber-7.7.4-SNAPSHOT-sources.jar
```
---
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Update release tag to vX.Y.Z

java/pom.xml
Tested:
With these changes, `mvn release:prepare` did commit and push the changes where it previously didn't.
Test's commits:
https://github.com/googlei18n/libphonenumber/commit/6018179a6c5372bf6d21201119f21acda121d6a1
https://github.com/googlei18n/libphonenumber/commit/89775601509bb739bb59961ab8e9d60e9f439794
b/34238872
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1505)
=> Add explicit SCM dependencies in pom.xml

cpp/src/phonenumbers/phonenumbermatcher.cc, cpp/src/phonenumbers/phonenumberutil.cc, cpp/src/phonenumbers/stringutil.cc, cpp/src/phonenumbers/stringutil.h
Refactoring change:
Adding more StrCat helper methods with more args to remove some temp vars in the phonenumbermatcher and phonenumberutil that were there to work around this restriction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1543)
=> Adding more StrCat helper methods with more args

cpp/src/phonenumbers/phonenumberutil.h
-- Updating the max allowed NSN length for C++ to be 17 (matches Java and JS).
-- Fixing a typo in a comment in the .h file while here and aligning a
comment better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1561)
=> Fixing .h file (C++) to match other versions

cpp/src/phonenumbers/phonenumberutil.cc, cpp/test/phonenumbers/phonenumberutil_test.cc, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, java/libphonenumber/test/com/google/i18n/phonenumbers/PhoneNumberUtilTest.java, javascript/i18n/phonenumbers/phonenumberutil.js, javascript/i18n/phonenumbers/phonenumberutil_test.js, pending_code_changes.txt
Fix for getNationalSignificantNumber to be robust in the face of malicious input (negative number of leading zeros in the phone number proto).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1576)
=> Fix for getNationalSignificantNumber to be robust

cpp/src/phonenumbers/geocoding/phonenumber_offline_geocoder.h, java/geocoder/src/com/google/i18n/phonenumbers/geocoding/PhoneNumberOfflineGeocoder.java, pending_code_changes.txt
Updating docs to:
- make them more consistent with each other
- explain why the empty string is sometimes returned when geocoding
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1605)
=> PhoneNumberOfflineGeocoder doc update

release_notes.txt
Two releases in 2012 were labeled as 2010.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1606)
=> Update typos in old release notes

java/libphonenumber/pom.xml
Ref #1642 
This adds a JAR target without included metadata. Third parties using this
variant may supply their own metadata via a custom MetadataLoader.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1643)
=> Add a no-metadata JAR variant

FAQ.md
Replacement for PR #1635 - explicitly addressing the reasons behind the missing assigned country calling codes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1681)
=> FAQ addition about country calling codes 388 and 991

cpp/src/phonenumbers/phonenumberutil.cc, cpp/test/phonenumbers/phonenumberutil_test.cc, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, java/libphonenumber/test/com/google/i18n/phonenumbers/PhoneNumberUtilTest.java, javascript/i18n/phonenumbers/phonenumberutil.js, javascript/i18n/phonenumbers/phonenumberutil_test.js, pending_code_changes.txt
This would previously have been thrown in C++ and Java if a number with a phone-context tag is entered (RFC3966 format) but no actual phone context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1690)
=> Handling possible out-of-bounds exception when parsing RFC3966 format

javascript/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1727)
=> Removing revision number in JS README, it's obsolete now we use github.

.travis.yml
Now the default environment omits ant-optional and the ant junit command doesn't work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1731)
=> Fixing Travis build

README.md
Currently the README suggest two 3rd party javascript ports of this library.
It doesn't expose any differences though making it confusing and difficult for the end users to figure out which one should they choose.
I added some simple key points explaining the difference between the two.
@seegno tell us what you think.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlei18n/libphonenumber/1846)
=> Clarify distinctions between the two javascript ports

resources/carrier/en/44.txt
Uses the most recent carrier data from Ofcom, with carrier names being changed to friendlier versions (brand/trading names).
Data has also been compressed to reduce duplicate prefixes, although the script has compressed it further than it used to be.
Generated using https://github.com/giggsey/GBCarrierGenerator (so can be run again).
A few questions about the company names:
=> Update GB (+44) carrier data from Ofcom

cpp/src/phonenumbers/phonenumberutil.cc, cpp/test/phonenumbers/phonenumberutil_test.cc, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, java/libphonenumber/test/com/google/i18n/phonenumbers/PhoneNumberUtilTest.java, javascript/i18n/phonenumbers/phonenumberutil.js, javascript/i18n/phonenumbers/phonenumberutil_test.js, pending_code_changes.txt
Make use of the recently introduced validation enum values IS_POSSIBLE_LOCAL_ONLY and INVALID_LENGTH.
Helps with e.g. short-code parsing where the short-code's prefix matches the nationalPrefix.
E.g. Iran has nationalPrefix=0 and short-codes 096\d{2} should be added. To ensure the "0" isn't stripped (but preserved as italian_leading_zero), we need to make sure that the parser doesn't consider the 0 as the national-prefix in this number.
This already worked if:
- nationalPrefix != prefix of short-code, or
- nationalPrefix == prefix of short code and:
- short-code matches generalDesc pattern but remainder doesn't, or
- remainder of short-code is too short to be a non-short-code.
The last bullet item is why 112 already works as US short-code although nationalPrefix=1.
The fix is necessary …
=> Improve parsing logic to be smarter about national-prefix detection & stripping.

README.md
The ownership of the C# port has changed, you will note that the old location https://github.com/aidanbebbington/libphonenumber-csharp/ redirects to the new location.
=> Update C# port link

README.md
libphonenumber-android repackages the library and replaces nonoptimal usage of `Class#getResourceAsStream()` with `AssetManager#open()` for android as suggested in [FAQ](https://github.com/googlei18n/libphonenumber/blob/e95e140dd7eeb898b9ebe1eee98ef63048ace1c0/FAQ.md#optimize-loads)
=> Add link to android-optimized port

cpp/src/phonenumbers/phonenumberutil.cc
This was not a bug (yet). The result won't change so I'm not including it in release notes.
This wasn't causing issues because UNKNOWN is actually the last value of PhoneNumberType, so the conditional at line 305 was just never true. However we introduced kMaxNumberType to be able to add new PhoneNumberType values more easily, and if we do, the new last value would not be included in the for loop (at that point there would be a bug), so fixing it now.
cl/172101896
=> Update kMaxNumberType stop condition

cpp/src/phonenumbers/phonenumberutil.h, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, javascript/i18n/phonenumbers/phonenumberutil.js
We say that "INTERNATIONAL and NATIONAL formats are consistent with the definition in ITU-T Recommendation E.123." This is not completely true as we follow local conventions which can include using '-' instead of whitespace (Mentioned in E.123 doc) as separators. PTAL at attached bug for more details.
=> Update Javadoc for PhoneNumberUtil.PhoneNumberFormat enum reg E.123 format rules we follow

cpp/CMakeLists.txt
Fixes porting issue on macOS and maybe elsewhere.
Fixes https://github.com/googlei18n/libphonenumber/issues/2044.
Ref https://github.com/Homebrew/homebrew-core/pull/21274
=> Use GNUInstallDirs to set LIBDIR

resources/carrier/en/976.txt
Updated from Communications Regulatory Commission of Mongolian.
http://www.crc.gov.mn/k/4L/36
Another source: http://www.wtng.info/wtng-976-mn.html
=> Updated Mongolian carrier prefixes

CONTRIBUTING.md
Differentiate what needs to be done for providing authoritative evidence (done over Issue Tracker) versus Pull Requests (done in GitHub).
=> CLA use cases

resources/carrier/en/351.txt
Updates from: https://www.anacom.pt/pnn/pesquisa.do.
TMN is now MEO and Optimus is now NOS (https://en.wikipedia.org/wiki/List_of_mobile_network_operators_of_Europe#Portugal)
351 92 are distributed according the needs of each provider.
=> Update for Portuguese providers

javascript/i18n/phonenumbers/phonenumberutil.js, javascript/i18n/phonenumbers/phonenumberutil_test.js
Presently we are supporting unicode characters of Russian extension characters manually in JS.
This should be changed in future by setting right flags.
Previous PR: https://github.com/googlei18n/libphonenumber/pull/2223
Surprisingly, we need not set unicode characters of upper case '\u0414\u041E\u0411'. This woks fine.
=> Manually support unicode version of Russian extension characters доб in RegEx

cpp/README
Change troubleshooting CMake on mac Protobuf path to .dylib
The .dylib file of protobuf is installed by Homebrew following the README instructions. There is no .so file on Mac to link to.
=> Change troubleshooting CMake on mac Protobuf path to .dylib

javascript/i18n/phonenumbers/asyoutypeformatter_test.html, javascript/i18n/phonenumbers/demo-compiled.html, javascript/i18n/phonenumbers/demo.html, javascript/i18n/phonenumbers/phonenumberutil.js, javascript/i18n/phonenumbers/phonenumberutil_test.html, javascript/i18n/phonenumbers/shortnumberinfo_test.html
Before this change, the `document.charset` of the HTML test files would be 'windows-1252' when accessed through the `file://` protocol, resulting in issues with library or test files containing non-ASCII symbols.
This patch ensures tests still run correctly when files contain non-ASCII symbols.
=> Ensure the test runner decodes files as UTF-8

java/pom.xml
- Issue: Staging repo is getting closed immediately after pushing staging binaries to Sonatype (i.e after running mvn release:perform). As per our mvn process / commands it should create an open staging repo and we close them manually after creating Maven PR like #2255. 
Note: This is to ensure the staging repo still in open state (to make any corrections/rerun) if anything is gone wrong in final steps of Maven release.
- History: This started happening after our introduction of nexus-staging-maven-plugin to avoid multiple staging repo are getting created in Sonatype. PR #2236
- Solution: Setting <skipStagingRepositoryClose> to true for same nexus-staging-maven-plugin
More details in and this solution is suggested at: https://issues.sonatype.org/browse/OSSRH-41613
Documentation referred: …
=> Configuring not to close staging repo automatically after pushing staging binaries to Sonatype

resources/carrier/en/40.txt
Zapp was bought by Telekom. 
https://en.wikipedia.org/wiki/Zapp_Mobile
And for example, 07887xxxxx is still a valid number.
=> added back Zapp network numbers

cpp/test/phonenumbers/shortnumberinfo_test.cc, java/libphonenumber/test/com/google/i18n/phonenumbers/ShortNumberInfoTest.java, javascript/i18n/phonenumbers/shortnumberinfo_test.js
Update ShortNumberInfo test regarding example number change for region AM. Unlike PhoneNumberUtilTest, ShortNumberInfoTest uses real metadata for unit testing.
=> Update ShortNumberInfo test regarding example number change.

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
- The Maven release is started before the merge of metadata update (PR #2276).
- So reverting the pom.xml updates and starting over Maven release again.
=> Reverting version number updates in pom.xml, done in PR #2277

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
The same previous update #2277 is reverted in #2280.
This is new roll-forward of original pom.xml updates.
=> Penmetsaa maven update

cpp/test/phonenumbers/shortnumberinfo_test.cc, java/libphonenumber/test/com/google/i18n/phonenumbers/ShortNumberInfoTest.java, javascript/i18n/phonenumbers/shortnumberinfo_test.js
As part of this change, we no more test the hardcoded example number.
=> Fixing brittle unit test of checking example short number.

cpp/src/phonenumbers/phonenumberutil.cc
Add a check that the FG is indeed in the national prefix before erasing it, in FormatInOriginalFormat. Matches java interpretation. It should always be there but if for some reason someone generates metadata with it not there we don't want to seg fault.
=> Defensive check added to FormatInOriginalFormat

java/demo/README, java/demo/pom.xml
- Our java demo artefact's dependency "commons-fileupload" is having a potential security vulnerability. GitHub notified about this. So updated version number from 1.3.2  to 1.3.3 (latest one)
- Updated same PR to mention additional mvn command "mvn clean install -U" that I have run because of errors like below. This makes sure that jar files with latest dev snapshot version are built and installed in the local Maven repository.  And this has to be done once at the java/ folder level and in present java/demo.
```[ERROR] Failed to execute goal on project demo: Could not resolve dependencies for project com.googlecode.libphonenumber:demo:jar:8.10.3-SNAPSHOT: The following artifacts could not be resolved: com.googlecode.libphonenumber:libphonenumber:jar:8.10.3-SNAPSHOT, …
```
=> Demo common libs v update

javascript/i18n/phonenumbers/phonenumberutil_test.js
Removing the code to convert specific digits to \d.
More details in PR #2295 and CL/222974757
Note: We encountered this JS unit test failure during release as we maintain it externally first.
=> JS changes for PR #2295

cpp/src/phonenumbers/phonenumbermatcher.cc, cpp/src/phonenumbers/phonenumbermatcher.h, cpp/test/phonenumbers/phonenumbermatcher_test.cc, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberMatcher.java, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, java/libphonenumber/test/com/google/i18n/phonenumbers/PhoneNumberMatcherTest.java, pending_code_changes.txt
Affects callers of the findNumbers interface with leniency strict grouping or exact match.
CL/235568327 plus a couple of tiny formatting changes to reduce diffs while I was there.
=> Application of alternate formats respects leading digits.

FAQ.md
Inspired from https://issuetracker.google.com/u/0/issues/129654594 where we mark a invalid number as valid but do not provide formatting.
=> FAQ on "Some 'valid' numbers are not formatting correctly."

java/carrier/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
Note: this is a maven build improvement.
Details:
- plugin version is upgraded: **1.15** -->> **1.17**
- plugin version is removed out of submodules into root pom.xml (i.e. plugin version can be changed easily)
=> 'animal-sniffer-maven-plugin' changes: version is upgraded and extracted into root pom.xml

java/carrier/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
Removing configuration of animal sniffer's maven pulgin version number at component level.
Note:
- This is being done to make sure the setup is clean to a working state, and avoid issues reported in #2356.
- The plugin version number is now mentioned at parent level java/libphonenumber/pom.xml
=> Made animal sniffer maven plugin version declared in one place

cpp/src/phonenumbers/asyoutypeformatter.cc, cpp/src/phonenumbers/phonenumberutil.cc, cpp/test/phonenumbers/phonenumberutil_test.cc, java/libphonenumber/src/com/google/i18n/phonenumbers/AsYouTypeFormatter.java, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, java/libphonenumber/test/com/google/i18n/phonenumbers/PhoneNumberUtilTest.java, javascript/i18n/phonenumbers/phonenumberutil.js, javascript/i18n/phonenumbers/phonenumberutil_test.js
Remove MX's mobile token value (1) from mobileTokenMap list in PhoneNumberUtil.
Update AYTF to not swallow input numbers like mobile token (1), which we are trimming of when asked to format, as AYTF should represent exact input digits. (This API is only in Java and CPP)
MX's mobile token value (1) has been abolished as part of dialling pattern updates in MX, during Aug 2019. https://www.itu.int/dms_pub/itu-t/oth/02/02/T020200008A0003PDFE.pdf
More details in cl/261295217 and cl/263086682
Notes: 
- Still using HashMap, not ImmutableMap.of() as it needs java 8 and to be consistent with other part of the existing code.
- This PR will be merged on after success completion of migration.
- Will update formatForMobileDialling() for MX case (api that returns most successful format of dialling …
=> Abolish MX's international mobile token (1)

cpp/src/phonenumbers/phonenumberutil.cc, cpp/test/phonenumbers/phonenumberutil_test.cc, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, java/libphonenumber/test/com/google/i18n/phonenumbers/PhoneNumberUtilTest.java, javascript/i18n/phonenumbers/phonenumberutil.js, javascript/i18n/phonenumbers/phonenumberutil_test.js, resources/PhoneNumberMetadataForTesting.xml
In coming metadata release: National prefix (06) will be present by default in national format for both fixed line and mobile numbers based on Wikipedia. So making the code ready.
For Hungary, there is special logic in formatNumberForMobileDialing() to manually add national prefix as earlier we are not adding based on metadata. So we are removing it as part of this change; and it is no more needed. Also removing the relevant test data and unit tests as because this is the only case tested for Hungary. More details in cl/265831383
Evidence: https://en.wikipedia.org/wiki/Telephone_numbers_in_Hungary
=> Hungary code changes

javascript/build.xml
I encountered some issues when building the javascript library. After successfully compiling the closure-compiler, I ran `ant -f javascript/build.xml compile-demo` as the javascript/README.md suggests. The first error I saw was:
```
[exec] java.lang.NullPointerException: No warning class for name: ambiguousFunctionDecl
[exec] 	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:980)
[exec] 	at com.google.javascript.jscomp.DiagnosticGroups.setWarningLevel(DiagnosticGroups.java:697)
[exec] 	at com.google.javascript.jscomp.AbstractCommandLineRunner.setWarningGuardOptions(AbstractCommandLineRunner.java:327)
[exec] 	at com.google.javascript.jscomp.AbstractCommandLineRunner.setRunOptions(AbstractCommandLineRunner.java:368)
[exec] 	at …
```
=> Fix javascript build issues

javascript/i18n/phonenumbers/phonenumberutil.js, pending_code_changes.txt
Updates the type annotations to indicate the inputs are required to be non-null.
Context: http://cl/296235173
=> Updates the type annotations in phonenumberutil.js

cpp/src/phonenumbers/utf/unicodetext.cc
Refer using std::string instead of global 'string' i.e to increase portablility, readability and also consistent. Cloning from cl/311566086
=> Refer using std::string instead of global 'string'

README.md
Change `depricated` to `deprecated` in README.md
=> Minor README.md spelling fix

metadata/src/test/java/com/google/i18n/phonenumbers/metadata/DigitSequenceTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/RangeSpecificationTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/RangeTreeTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/i18n/PhoneRegionTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/i18n/SimpleLanguageTagTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/model/AltFormatSpecTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/model/FormatSpecTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/table/AssignmentTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/table/ChangeTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/table/ColumnGroupTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/table/ColumnTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/table/CsvParserTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/table/CsvTableTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/table/RangeTableTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/table/SchemaTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/testing/AssertUtil.java
PiperOrigin-RevId: 320004982
Code by Googler's only, so CLA is implicit.
=> Use "in house" helper for assertThrows() which is otherwise only available internally.

metadata/pom.xml, metadata/src/main/java/com/google/i18n/phonenumbers/metadata/RangeSpecification.java, metadata/src/main/java/com/google/i18n/phonenumbers/metadata/model/FormatSpec.java, metadata/src/main/java/com/google/i18n/phonenumbers/metadata/model/RangesTableSchema.java, metadata/src/main/java/com/google/i18n/phonenumbers/metadata/table/RangeTable.java, metadata/src/main/java/com/google/i18n/phonenumbers/metadata/table/Schema.java
PiperOrigin-RevId: 320135887
The JavaDoc still (deliberately) doesn't use @param and @return everywhere, but these "errors" are suppressed by the "-missing" option. Overly repetitive documentation, where information is stated in the field/method description and repeated in parameter/return declarations adds maintenance burden for very little benefit.
Once this is in, "mvn javadoc:javadoc" should produce the public JavaDoc site under <project>/target/site/apidocs.
=> Fixing up the JavaDoc to remove serious HTML violations.

metadata/src/test/java/com/google/i18n/phonenumbers/metadata/model/AltFormatsSchemaTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/model/CommentsSchemaTest.java, metadata/src/test/java/com/google/i18n/phonenumbers/metadata/table/CsvTableTest.java
As the new line characters are not well trimmed or joined, the results are not as expected in export* API unit tests.
Eg:
```
missing (2)   : Region ; Label          ; Comment, US     ; XML_FIXED_LINE ; "Hello World"
, US     ; XML_FIXED_LINE ; "Hello World" Comment
---
expected      : [Region ; Label          ; Comment, US     ; XML_FIXED_LINE ; "Hello World"]
] US     ; XML_FIXED_LINE ; "Hello World"; Comment
at com.google.i18n.phonenumbers.metadata.model.CommentsSchemaTest.testSimple_export(CommentsSchemaTest.java:55)
```
Found these unit test issues when buidling the Windows machine. Some notes in cl/346717586.
=> Fix the unit test case issues in DOS/Windows platform by picking the new line char dynamically.

cpp/CMakeLists.txt
Original commit from  Timur Kristóf (#2363)
Add ability for the C++ library to link against protobuf-lite. .
USE_PROTOBUF_LITE - When this is set to ON then it links against protobuf-lite instead of the full version of protobuf. As far as I could see the metadata has option optimize_for = LITE_RUNTIME; so it should be safe to use the lite version. This is useful when you want to save some disk space. The default is OFF.
see https://github.com/google/libphonenumber/pull/2363 for original PR
discussion about protobuf vs protobif lite :
https://stackoverflow.com/questions/6405767/protocol-buffer-lite-versus-regular-protocol-buffer
@Venemo  @penmetsaa
=> Add new c++ build options for use protobuf-lite

cpp/src/phonenumbers/asyoutypeformatter.cc, cpp/src/phonenumbers/normalize_utf8.h, cpp/src/phonenumbers/phonenumbermatch.cc, cpp/src/phonenumbers/phonenumbermatcher.cc, cpp/src/phonenumbers/phonenumberutil.cc, cpp/src/phonenumbers/regexp_adapter_icu.cc, cpp/src/phonenumbers/stringutil.cc, cpp/src/phonenumbers/unicodestring.h, cpp/src/phonenumbers/utf/unicodetext.cc, cpp/src/phonenumbers/utf/unicodetext.h, cpp/src/phonenumbers/utf/unilib.cc, cpp/src/phonenumbers/utf/unilib.h
In visual studio 2019 x64 target, size_t are 64 bits and int are 32 bits
This commit cast some length of string from size_t to int to fix warnings
=> Fix somes warning when compiling VS2019 target

cpp/src/phonenumbers/phonenumbermatcher.cc
Needed for std::unique_ptr. Building was broken previously on Ubuntu 18.04.
=> Add missing include

cpp/src/phonenumbers/base/memory/scoped_ptr.h
This PR contain a very simple fix for a unused parameter warning
=> warning fix unused-parameter

cpp/CMakeLists.txt
- When building as a dependency using cmake's add_subdirectory() use the
current source directory instead of the top level source tree.
Previously it was not possible to use libphonenumber in such a way, especially when linking statically.
=> Fix building as dependency with add_subdirectory()

javascript/build.xml, javascript/i18n/phonenumbers/phonemetadata.pb.js, javascript/i18n/phonenumbers/phonenumber.pb.js
I tried building the JS demo using the latest release of the Google Closure compiler. It failed with the following error:
```
$ ant -f javascript/build.xml compile-demo
Buildfile: /home/senya/libphonenumber-tools/libphonenumber/javascript/build.xml
compile-demo:
[exec] /home/senya/libphonenumber-tools/libphonenumber/javascript/../../closure-library/closure/bin/build/closurebuilder.py: Scanning paths...
[exec] /home/senya/libphonenumber-tools/libphonenumber/javascript/../../closure-library/closure/bin/build/closurebuilder.py: 1657 sources scanned.
[exec] /home/senya/libphonenumber-tools/libphonenumber/javascript/../../closure-library/closure/bin/build/closurebuilder.py: Building dependency tree..
[exec] /home/senya/libphonenumber-tools/libphonenumber/javascript/../../closure-library/closure …
```
=> Fix the JS demo compilation with the latest Closure compiler

cpp/src/phonenumbers/phonenumberutil.cc, cpp/test/phonenumbers/phonenumberutil_test.cc, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, java/libphonenumber/test/com/google/i18n/phonenumbers/PhoneNumberUtilTest.java, javascript/i18n/phonenumbers/phonenumberutil.js, javascript/i18n/phonenumbers/phonenumberutil_test.js, pending_code_changes.txt, resources/phonemetadata.proto, tools/java/common/test/com/google/i18n/phonenumbers/BuildMetadataFromXmlTest.java
After this change, the API always use preferred intl prefix if present, not just for numbers with a non-unique IDD. This means we will output "8~10" as the prefix if calling `formatOutOfCountryCallingNumber` instead of "810" for some regions that have this tilde in their prefix [designates that the user should wait before continuing to dial].
P.S: If `formatOutOfCountryCallingNumber()` API has returned format with wrong international exit code for region calling from, [please report the issue](https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md#filing-a-metadata-issue) as it has to be corrected in metadata.
=> Always use preferred intl prefix if present

javascript/i18n/phonenumbers/phonenumberutil_test.js
```goog.array.contains(arr, obj)```, is generous to take any object type, while ES5 ```<array_type>.includes()``` is not.
https://google.github.io/closure-library/api/goog.array.html This must have been cought as part of change PR #2627; but I missed testing it. Found during the metadata release test.
=> Unit test fix, that missed testing as part of commit #5c309c5

cpp/src/phonenumbers/utf/unicodetext.cc
There a few places where messages are written direct to `stderr` instead of using the logging mechanism. Our application uses structured logging on `stderr`, in the form of a stream of newline-separated JSON, and the insertion of non-JSON text breaks the validity of the stream.
This PR sends the messages through `libphonenumber`'s log mechanism instead. It breaks the code structure slightly because the code now uses the logger inside the `utf` module. However, there isn't any circularity because the logger doesn't use the `utf` code.
See [Issue 206677455](https://issuetracker.google.com/issues/206677455) for additional discussion and background.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
=> Replace direct output to stderr with logging

cpp/src/phonenumbers/normalize_utf8.h, cpp/src/phonenumbers/phonenumberutil.cc, cpp/src/phonenumbers/unicodestring.h, cpp/src/phonenumbers/utf/unicodetext.cc, cpp/src/phonenumbers/utf/unicodetext.h, cpp/test/phonenumbers/phonenumberutil_test.cc, cpp/test/phonenumbers/utf/unicodetext_test.cc
Keep track of whether unicode strings were created from valid UTF-8 and use this to abort operations that use these strings later.
Typically, this is done by returning an empty string when a modified string is being produced, since an empty string is never a valid phone number.
See [b/206677455](https://issuetracker.google.com/issues/206677455)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/libphonenumber/2698)
=> Be stricter about invalid UTF-8 input

cpp/src/phonenumbers/stringutil.cc
This very minor, trivial and risk free commit fix
introduced in 8.12.45 with #2734
error: ignoring return value of function declared with 'warn_unused_result' attribute [-Werror,-Wunused-result]"
Without this fix, I cannot build using clang++13
@penmetsaa @jeaiii @katbohm
=> fix build error with clang and gcc "

cpp/src/phonenumbers/shortnumberinfo.cc
Inspired from cl/434264801
If there are any such replaceable code snippets (s/iterators/auto), will do in my next cleanup.
=> Using CPP11 'auto' instead of iterators

cpp/src/phonenumbers/stringutil.cc, cpp/test/phonenumbers/stringutil_test.cc
Fix for UT breakage after https://github.com/google/libphonenumber/pull/2742.
```
[ RUN      ] StringUtilTest.safe_strtou64
/usr/local/google/home/penmetsaa/github_lab/libphonenumber/cpp/test/phonenumbers/stringutil_test.cc:139: Failure
Expected equality of these values:
18446744073709551615ULL
Which is: 18446744073709551615
n
Which is: 0
```
Though there is a failure in conversion, fortunately the job is done, though absl mark it as [unspecified state](https://github.com/abseil/abseil-cpp/blob/5ed77665c4d697f657fa1362b5a482450f858cdc/absl/strings/numbers.h#L63) 
Looks like just "void" is better sol in this case. More details there.
=> Making it clear that safe_strtou64 kind of string to int conversion apis fail when non decimal chars are present.

cpp/CMakeLists.txt, tools/cpp/CMakeLists.txt
Currently, CMake is configured to download and build abseil from source
whenever `BUILD_GEOCODER` is set to `ON`. Let's allow users to use a
pre-existing installation of abseil by checking for one first before
attempting to download and build another one.
If CMake finds a pre-existing installation of abseil, it will use that
instead.
We need to allow the user to override `CMAKE_CXX_STANDARD` because they
may have built abseil with a newer standard than C++11. Attempting to
build libphonenumber with C++11 will fail if abseil was built with a
newer C++ standard.
Closes #2772.
=> Use a system-installed abseil when available

cpp/README, tools/cpp/CMakeLists.txt
- We are cloning only a particular version of the abseil-cpp so that we
are not commiting to catch up with new build requirements of that
library. Eg: In recent absl-cop release C++14 is made as minimum
version to build the library.
- **Error details in b/239501609**
- Readme update w.r.t new abseil-cpp dependency changes i.e after
#2791
=> Fixating the absl-cpp version that we download and cpp readme update after #2791

java/demo/pom.xml
As release plugin only runs till ```verify``` phase during ```release:prepare```,
the class files are not being part of the demo bundle.
Now this ```exec plugin (soy-compiler)``` will run at ```verify``` phase itself
=> Update the soy-compiler running phase

README.md
Adds the Swift project [PhoneNumberKit](https://github.com/marmelroy/PhoneNumberKit) to the README for discoverability.
The motivation for this addition is that the currently linked iOS project, [libPhoneNumber-iOS](https://github.com/iziz/libPhoneNumber-iOS), is no longer maintained (last committed in 2021, last version published to cocoapods in 2019) by the author. The proposed Swift project is also based on libPhoneNumber, but is actively maintained and the author is regularly accepting pull requests.
=> Add Swift project to README

cpp/CMakeLists.txt
- The project currently fails to find abseil and gtest while building` libphonenumber/tools/cpp` because dependency resolutions have been consolidated in `libphonenumber/cpp`. This commit proposes a BUILD_TOOLS_ONLY option be added to the main project to allow building tools/cpp without duplicating common dependencies.
- In essence, to build libphonenumber/tools/cpp, do `cmake -S "path/to/libphonenumber/cpp" -DBUILD_TOOLS_ONLY=ON`
- This also solves the issue of ["Absl not being able to Install in super builds"](https://github.com/google/libphonenumber/pull/2818#issuecomment-1371867829)
=> CPP: Add BUILD_TOOLS_ONLY option

cpp/CMakeLists.txt
This commit resolves an issue with duplicate generation of metadata.h.
=> CPP: Fix typo in arguments to add_metadata_gen_target()

java/pom.xml
- We are getting errors like ```java.lang.NoClassDefFoundError: Could not initialize class org.mockito.internal.creation.cglib.ClassImposterizer$3``` during release steps like ```mvn clean deploy ```; Happening in ```mvn test``` as it is UT error whenever we tried mock and object.
- After checking online https://github.com/powsybl/powsybl-diagram/issues/398 and https://github.com/mockito/mockito/issues/638, it looks like we need to bump up Mockito's version inorder to be compatible with newer Java 17+ versions.
- For our build, we are using newer open JDK 17 from our last builds. I am not sure why this has not happened last time.
- As Mockito-all is deprecated and not needed, moved to Mockito core based on https://www.baeldung.com/mockito-core-vs-mockito-all
- Moved to recent (but a bit …
=> Switch to Mockito Core and bump up its version to be in compatible with newer Java 17+ versions.

java/demo/pom.xml
- Got this error when ran ```mvn deploy```
```
Error injecting constructor, java.lang.ExceptionInInitializerError
at org.apache.maven.plugin.war.WarMojo.<init>(Unknown Source)
while locating org.apache.maven.plugin.war.WarMojo
```
- Fix is inspired from https://stackoverflow.com/questions/66920567/error-injecting-org-apache-maven-plugin-war-warmojo
=> Bumpup war plugin version for demo site as the default Maven's one is not compatible with JDK17

java/pom.xml
Looks like after the latest bumpup of java version (i.e system level JDK to JDK11- just during the build time), the modular system is not going well with  nexus-staging-maven-plugin. Hence the error:
```
ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy (injected-nexus-deploy) on project libphonenumber-parent: Execution injected-nexus-deploy of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy failed: An API incompatibility was encountered while executing org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8:deploy: java.lang.ExceptionInInitializerError: null
[ERROR] -----------------------------------------------------
[ERROR] realm =    extension>org.sonatype.plugins:nexus-staging-maven-plugin:1.6.8
[ERROR] strategy = …
```
=> Bump up the version of Staging plugin as it is failing to access java.base mudule's java.util apis

javascript/i18n/phonenumbers/phonenumberutil.js
This change fixes err:
```
javascript/libphonenumber/i18n/phonenumbers/phonenumberutil.js:4389:10: ERROR - [JSC_JSDOC_MISSING_TYPE_WARNING] Missing type declaration.
4389|  * @param numberToExtractFrom
```
=> Fixing JSC_JSDOC_MISSING_TYPE_WARNING; The type declaration is missing in new API extractPhoneContext_

.github/CODEOWNERS
- Even now, only the members of the team can only approve the changes, but this is made evident and in future we can make different  members/team to own a path.
- This change is inspired from recent security recommendations from Github. b/275500757
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
- Made necessary security changes, like master "is now read-only", "min 2 reviews needed before merge".. etc
https://github.com/google/libphonenumber/settings/branches
=> Adding CODEOWNERS so the approvers (of PRs) were organized

cpp/CMakeLists.txt, tools/cpp/CMakeLists.txt
Do not overwrite binary settings like C++ version number.
For example this breaks [`ABSL_PROPAGATE_CXX_STD`](https://github.com/abseil/abseil-cpp/blob/efb035a5973b60d35ed8fcaa43e6736936a96173/CMakeLists.txt#L73-L78).
=> Inherit C++ version number

README.md
This is a port for the [Gleam programming language](https://gleam.run/)
=> Added `phony`, a port for Gleam

java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java
Below methods of phonenumberutil.format are currently returning '0' it should return 'empty'
1. phoneNumberUtil.format(new PhoneNumber(), PhoneNumberUtil.PhoneNumberFormat.NATIONAL)
2. phoneNumberUtil.format(new PhoneNumber(), PhoneNumberUtil.PhoneNumberFormat.INTERNATIONAL)
=> Update  phonenumberutil.format to return 'empty' instead of value "0".

cpp/src/phonenumbers/asyoutypeformatter.h, cpp/src/phonenumbers/base/synchronization/lock_posix.h, cpp/src/phonenumbers/geocoding/area_code_map.h, cpp/src/phonenumbers/geocoding/default_map_storage.h, cpp/src/phonenumbers/geocoding/mapping_file_provider.h, cpp/src/phonenumbers/geocoding/phonenumber_offline_geocoder.h, cpp/src/phonenumbers/phonenumbermatch.h, cpp/src/phonenumbers/phonenumberutil.cc, cpp/src/phonenumbers/phonenumberutil.h, cpp/src/phonenumbers/regex_based_matcher.h, cpp/src/phonenumbers/regexp_adapter_icu.cc, cpp/src/phonenumbers/regexp_cache.h, cpp/src/phonenumbers/shortnumberinfo.h, cpp/test/phonenumbers/asyoutypeformatter_test.cc, cpp/test/phonenumbers/phonenumberutil_test.cc, cpp/test/phonenumbers/shortnumberinfo_test.cc
Remove uses of the deprecated DISALLOW_COPY_AND_ASSIGN in favor of explicitly deleted constructors and assignment operators.
=> Mandlil patch 2

cpp/src/phonenumbers/phonenumberutil.cc, cpp/test/phonenumbers/phonenumberutil_test.cc, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, java/libphonenumber/test/com/google/i18n/phonenumbers/PhoneNumberUtilTest.java
After deleting the dialing tokens (01/02/044/045/1), the national prefix becomes empty so the condition is failing and returns 0.
=> Area code information lost for all MX numbers in v8.13.38 metadata update

java/carrier/pom.xml, java/demo/pom.xml, java/geocoder/pom.xml, java/internal/prefixmapper/pom.xml, java/libphonenumber/pom.xml, java/pom.xml
Reverts google/libphonenumber#3672
While doing android release, build for metadata files was performed but it was not able to find the javadoc. Hence, the build failed.
=> Revert "Kkeshava maven update"

javascript/i18n/phonenumbers/phonenumberutil.js
Without "()", when many conditions exist and former one is matched, it returns the wrong value. So adding "()" for the regex
I think it doesn't happen in Java and cpp
[related issue] (raised by myself)
https://issuetracker.google.com/issues/383824582
[java]
https://github.com/google/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/internal/RegexBasedMatcher.java#L49-L56
[cpp]
https://github.com/google/libphonenumber/blob/master/cpp/src/phonenumbers/regex_based_matcher.cc#L51-L65
=> Add "()" when string.match() is executed in js

cpp/src/phonenumbers/phonenumberutil.cc, cpp/test/phonenumbers/phonenumberutil_test.cc, java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java, java/libphonenumber/test/com/google/i18n/phonenumbers/PhoneNumberUtilTest.java, pending_code_changes.txt
This is to ensure that the extension is not included twice in the formatted number.
Unlike the Java version, the C++ version didn't format extensions at all which is fixed in this change.
Context: b/309836518
=> Strip extension before appending formatted extension.

cpp/CMakeLists.txt
In 9.0.1, cpp CMakeList.txt VERSION definition is still 8.13.0. It should be updated to 9.0.0.
=> Update cpp CMakeList.txt VERSION from 8.13.0 to 9.0.0.

cpp/test/phonenumbers/fuzz_matcher.cc
This fixes a simple memory leak in fuzz_matcher.cc. Mentioned in https://github.com/google/oss-fuzz/pull/13227
Leak happens because we don't free the ICURegExpFactory
=> fix memory leak in fuzz_matcher.cc

java/pom.xml
As of June 30, 2025 OSSRH has reached end of life and has been shut down. All OSSRH namespaces have been migrated to Central Publisher Portal. 
https://central.sonatype.org/pages/ossrh-eol/#process-to-migrate
=> Updated OSSRH(Nexus repository) to Central Portal to upload jars in maven

.github/workflows/java-unit-test.yml, java/pom.xml
By adding GPG plugin outside the profile, we are facing issue with mvn install command. it is giving signin issue.
To avoid that reverting plugin changes.
=> Revert Gpg plugin changes
